### ISSUE TITLE
Stick by default to top

### ISSUE THREAD

**Issue by Bitaru** [soenkekluth/react-sticky-state#1]
Hi, i just tried to set sticky-state to work in my project and found that nothing will happen if no 'top' or 'bottom' property was set to .sticky class. So, to make it work we must always set top: 0.
In my opinion, will be better to set default sticky to top, by changing [line](https://github.com/soenkekluth/react-sticky-state/blob/master/index.js#L265) to `if (bottom === null)`

**Comment by soenkekluth** [comment]
yes thats the native behavior and no issue. sticky needs position top or bottom to be set.
react-sticky-state just adds state to position:sticky and polyfills the missing feature.
your job is to set top or bottom to your chosen value.
