### ISSUE TITLE
onScroll not called when scrollTarget is a react component after unmount/remount

### ISSUE THREAD

**Issue by juhaelee** [soenkekluth/react-sticky-state#3]
@soenkekluth 

I found that the the [`onScroll`](https://github.com/soenkekluth/react-sticky-state/blob/master/index.js#L408) handler is not being called when the scrollTarget is a react component and the component gets unmounted (then later again mounted). The use case for this is when you're using something like react-router and you click the back button and the component unmounts, and you go back to the route, and the component remounts. The [`FastScroll.getInstance`](https://github.com/soenkekluth/react-sticky-state/blob/master/index.js#L375) is retrieving an instance that doesn't exactly match the previously unmounted react component. 

A potential fix for this could be to clear the instance on componentWillUnmount if the scrollTarget is a react component? https://github.com/soenkekluth/react-sticky-state/blob/master/index.js#L437

**Comment by soenkekluth** [comment]
@juhaelee you are right. the problem is solved by the current version
