### ISSUE TITLE
Uncaught TypeError: Cannot set property 'scroll:start' of null

### ISSUE THREAD

**Issue by henrikra** [soenkekluth/react-sticky-state#6]
I am getting this error when I navigate second time to route where sticky element is. I am using react-router. Lets say I start at localhost:3000/home then I go to localhost:3000/epic-page where my sticky element is. Then I go back to home and back to epic-page this when I get the error and sticky doesn't work anymore.

**Comment by soenkekluth** [comment]
@henrikra will look into it

**Comment by soenkekluth** [comment]
@henrikra please try v2.0.1 and give me feedback

**Comment by henrikra** [comment]
Looks like it is working now! What was the problem?

**Comment by soenkekluth** [comment]
I did not destroy the instances properly and scroll listeners were not removed.
glad that it works. a new version with some optimizations is on its way.... I will close...
